version: '3.8'

services:
  # Backend Service (Node.js/Express)
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - uploads-data:/app/public/uploads
    env_file:
      - ./backend/.env
    environment:
      # Connection string for MongoDB running in another container
      - MONGO_URI=mongodb://mongo:27017/e-commerce-db
      - PORT=3001
    depends_on:
      - mongo
    networks:
      - ecom-network

  # Frontend Service (Next.js Production)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - NEXT_PUBLIC_API_URL=http://159.89.7.177:3001/api/v1
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://159.89.7.177:3001/api/v1
    depends_on:
      - backend
    networks:
      - ecom-network

  # MongoDB Service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      # Persist database data
      - mongo-data:/data/db
    networks:
      - ecom-network

# Define the network
networks:
  ecom-network:
    driver: bridge

# Define the volume for MongoDB data persistence
volumes:
  mongo-data:
  uploads-data:
