version: '3.8'

services:
  # Backend Service (Node.js/Express) - Development
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      # Mount the src folder for hot-reloading
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/tsconfig.json:/app/tsconfig.json
      - uploads-data:/app/public/uploads
    env_file:
      - ./backend/.env
    environment:
      # Connection string for MongoDB running in another container
      - MONGO_URI=mongodb://mongo:27017/e-commerce-db
      - PORT=3001
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:3000
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - mongo
    networks:
      - ecom-network
    command: npm run dev

  # Frontend Service (Next.js) - Development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:3001/api/v1
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api/v1
      - NODE_ENV=development
    volumes:
      # Mount source code for hot reloading
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/next.config.ts:/app/next.config.ts
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/postcss.config.js:/app/postcss.config.js
      - ./frontend/package.json:/app/package.json
      - ./frontend/tsconfig.json:/app/tsconfig.json
    depends_on:
      - backend
    networks:
      - ecom-network

  # MongoDB Service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      # Persist database data
      - mongo-data:/data/db
    networks:
      - ecom-network

# Define the network
networks:
  ecom-network:
    driver: bridge

# Define the volume for MongoDB data persistence
volumes:
  mongo-data:
  uploads-data:
